on:
  issues:
    types: [opened, edited, deleted]
name: New Issue
jobs:
  new_issue:
    name: New Issue Job
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      YOUTUBE_CLIENT_JSON: ${{ secrets.YOUTUBE_CLIENT_JSON }}
      YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Google API PHP Client
        run: composer require google/apiclient

      - name: Update Task Manager with PHP
        run: php .github/workflows/tasker.php

      - name: Commit changes
        run: |
          git config --global user.name 'Github Actions Bot'
          git config --global user.email ${{ secrets.GITHUB_EMAIL }}
          git add -A
          git commit -m ':sparkles: tasks updated.' || echo "No changes to commit"

      - name: Push Tasks to Repo
        run: git push || echo "No changes to push"
